<?php
/**
 * The Sensula design's look for the starter catalogue: illustration, colours, size label, top picks,
 * launch dates, linked sizes and scents, fragrance notes, and category and brand settings.
 *
 * @package NexusBeauty
 */

defined( 'ABSPATH' ) || exit;

return array(
	'products'   => array(
		'NX-AXIS-Y-5' => array( 'shape' => 'dropper', 'tone' => '#e2a33b', 'bg' => '#fbf1df', 'size' => '5 ml mini', 'featured' => true, 'days_old' => 120 ),
		'NX-AXIS-Y-50' => array( 'shape' => 'dropper', 'tone' => '#e2a33b', 'bg' => '#fbf1df', 'size' => '50 ml', 'featured' => false, 'days_old' => 120 ),
		'NX-DR-ALTHEA-345' => array( 'shape' => 'jar', 'tone' => '#b3a0c9', 'bg' => '#f0ebf6', 'size' => '50 ml', 'featured' => true, 'days_old' => 120 ),
		'NX-PONDS-GEL' => array( 'shape' => 'jar', 'tone' => '#7fa7b8', 'bg' => '#e9f1f4', 'size' => '50 ml', 'featured' => false, 'days_old' => 120 ),
		'NX-LOREAL-GLYCOLIC' => array( 'shape' => 'tube', 'tone' => '#b04a6b', 'bg' => '#f7e5eb', 'size' => 'Face wash', 'featured' => false, 'days_old' => 120 ),
		'NX-GARNIER-VITC' => array( 'shape' => 'dropper', 'tone' => '#e2a33b', 'bg' => '#fbf1df', 'size' => 'Serum', 'featured' => false, 'days_old' => 120 ),
		'NX-MEDICUBE-PDRN' => array( 'shape' => 'dropper', 'tone' => '#e58aa8', 'bg' => '#fbe7ee', 'size' => 'Serum', 'featured' => false, 'days_old' => 0 ),
		'NX-ANUA-AZELAIC' => array( 'shape' => 'dropper', 'tone' => '#9bb79e', 'bg' => '#eaf2eb', 'size' => 'Serum', 'featured' => false, 'days_old' => 0 ),
		'NX-BOJ-RELIEF-SUN' => array( 'shape' => 'tube', 'tone' => '#f0c24b', 'bg' => '#fdf5dc', 'size' => '50 ml', 'featured' => true, 'days_old' => 120 ),
		'NX-ESTELIN-70' => array( 'shape' => 'tube', 'tone' => '#c99a78', 'bg' => '#f6ece4', 'size' => 'Sunscreen', 'featured' => true, 'days_old' => 120 ),
		'NX-NEOBRELLA-60' => array( 'shape' => 'tube', 'tone' => '#f0c24b', 'bg' => '#fdf5dc', 'size' => 'Sunscreen', 'featured' => false, 'days_old' => 120 ),
		'NX-TOCOBO-STICK' => array( 'shape' => 'tube', 'tone' => '#9bb79e', 'bg' => '#eaf2eb', 'size' => 'Stick', 'featured' => false, 'days_old' => 0 ),
		'NX-SKIN1004-SUN' => array( 'shape' => 'tube', 'tone' => '#7fa7b8', 'bg' => '#e9f1f4', 'size' => 'Sun serum', 'featured' => false, 'days_old' => 0 ),
		'NX-REDERM-TRESSFIX' => array( 'shape' => 'bottle', 'tone' => '#9bb79e', 'bg' => '#eaf2eb', 'size' => 'Shampoo', 'featured' => true, 'days_old' => 120 ),
		'NX-JENPHARM-ANAGROW' => array( 'shape' => 'bottle', 'tone' => '#7fa7b8', 'bg' => '#e9f1f4', 'size' => 'Shampoo', 'featured' => false, 'days_old' => 120 ),
		'NX-FINO-MASK' => array( 'shape' => 'jar', 'tone' => '#c68a3a', 'bg' => '#f8eedf', 'size' => 'Mask', 'featured' => false, 'days_old' => 120 ),
		'NX-MIELLE-ROSEMARY' => array( 'shape' => 'jar', 'tone' => '#5f8f6a', 'bg' => '#e6f0e8', 'size' => 'Masque', 'featured' => false, 'days_old' => 120 ),
		'NX-VASELINE-GLUTA' => array( 'shape' => 'pump', 'tone' => '#b04a6b', 'bg' => '#f7e5eb', 'size' => 'Lotion', 'featured' => true, 'days_old' => 120 ),
		'NX-VASELINE-GEL-OIL' => array( 'shape' => 'pump', 'tone' => '#d9b48f', 'bg' => '#f7efe6', 'size' => 'Gel oil', 'featured' => false, 'days_old' => 120 ),
		'NX-KN-VP' => array( 'shape' => 'perfume', 'tone' => '#c9a55a', 'bg' => '#f6efdc', 'size' => '100 ml', 'featured' => true, 'days_old' => 2 ),
		'NX-KN-OUD' => array( 'shape' => 'perfume', 'tone' => '#8a4b2f', 'bg' => '#f3e6dc', 'size' => '100 ml', 'featured' => false, 'days_old' => 2 ),
		'NX-KN-MUSK' => array( 'shape' => 'perfume', 'tone' => '#86aec2', 'bg' => '#e8f1f5', 'size' => '100 ml', 'featured' => false, 'days_old' => 2 ),
		'NX-KN-VP-30' => array( 'shape' => 'perfume', 'tone' => '#c9a55a', 'bg' => '#f6efdc', 'size' => '30 ml', 'featured' => false, 'days_old' => 2 ),
		'NX-HYPE-FRUIT' => array( 'shape' => 'bottle', 'tone' => '#e0708a', 'bg' => '#fbe6eb', 'size' => '150 ml', 'featured' => false, 'days_old' => 120 ),
		'NX-MEDORA-MATTE' => array( 'shape' => 'lipstick', 'tone' => '#9e2f4a', 'bg' => '#f6e2e7', 'size' => 'Lipstick', 'featured' => true, 'days_old' => 120 ),
		'NX-SWISS-MISS-60' => array( 'shape' => 'lipstick', 'tone' => '#b5655a', 'bg' => '#f6e6e2', 'size' => 'Lipstick', 'featured' => false, 'days_old' => 120 ),
		'NX-GARNIER-MEN-ACNO' => array( 'shape' => 'tube', 'tone' => '#3c3f44', 'bg' => '#e8e9eb', 'size' => 'Face wash', 'featured' => false, 'days_old' => 120 ),
		'NX-RIVAJ-BEARD' => array( 'shape' => 'dropper', 'tone' => '#c68a3a', 'bg' => '#f8eedf', 'size' => 'Beard oil', 'featured' => false, 'days_old' => 120 ),
		'NX-DAISY-PLUS' => array( 'shape' => 'tube', 'tone' => '#e38fb0', 'bg' => '#fbe8f0', 'size' => 'Pack', 'featured' => false, 'days_old' => 120 ),
		'NX-ST-IVES-APRICOT' => array( 'shape' => 'tube', 'tone' => '#e0915a', 'bg' => '#fcece0', 'size' => 'Scrub', 'featured' => false, 'days_old' => 120 ),
		'NX-DOVE-BODY-POLISH' => array( 'shape' => 'jar', 'tone' => '#c9a0b8', 'bg' => '#f6ecf2', 'size' => 'Body polish', 'featured' => false, 'days_old' => 120 ),
		'NX-CETAPHIL-GENTLE' => array( 'shape' => 'pump', 'tone' => '#7fa7b8', 'bg' => '#e9f1f4', 'size' => 'Cleanser', 'featured' => false, 'days_old' => 120 ),
		'NX-REDERM-CLARIDERM' => array( 'shape' => 'tube', 'tone' => '#9bb79e', 'bg' => '#eaf2eb', 'size' => 'Face wash', 'featured' => false, 'days_old' => 120 ),
		'NX-FEATHER-FLAMINGOS' => array( 'shape' => 'tube', 'tone' => '#e9a0a8', 'bg' => '#fcebed', 'size' => 'Pack', 'featured' => false, 'days_old' => 120 ),
	),
	// Extra details per product (meta keys without the leading underscore are added as _nx_*).
	'details'    => array(
		'NX-AXIS-Y-5'  => array( 'group' => 'axis-y-glow-serum', 'choice' => '5 ml mini', 'choice_tag' => 'Try it first' ),
		'NX-AXIS-Y-50' => array( 'group' => 'axis-y-glow-serum', 'choice' => '50 ml', 'choice_tag' => 'Best value' ),
		'NX-KN-VP'     => array(
			'group'        => 'koh-e-noor-vanilla',
			'choice'       => '100 ml',
			'choice_tag'   => 'Most popular',
			'scent_group'  => 'koh-e-noor-mists',
			'scent'        => 'Vanilla Pistachio',
			'notes'        => "Top | Pistachio, pear\nHeart | Vanilla orchid, almond milk\nBase | White musk, tonka, sandalwood",
			'wear'         => "Skin | 45 | 3–4 h\nHair | 90 | 6–8 h\nClothes | 100 | 6–8 h+",
			'facts'        => "What it is | A hair and body mist with more fragrance oil than a body spray\nWear time | 3–4 hours on skin, 6–8 hours on hair and clothes\nBest for | Everyday wear, after a shower, freshening up hair\nHair-friendly | Low alcohol with panthenol, so it won't dry your hair\nSize | 100 ml, about 900 sprays\nMade in | Pakistan · Cruelty-free\nShelf life | 36 months unopened, 12 months after opening",
			'fbt_title'    => 'Make it last all day',
			'fbt_text'     => 'Lotion first, then the mist. Scent lasts longer on moisturised skin.',
			'faq'          => "Is it safe to spray on my hair? | Yes. The formula has a low level of alcohol plus panthenol, so it scents hair without drying it out. Spray from about 20 cm onto the lengths, not the roots.\nDoes it contain alcohol? | Yes, a low level of cosmetic-grade alcohol. It helps the mist dry quickly and spread the scent evenly.\nHow long does the scent last? | About 3–4 hours on skin and 6–8 hours on hair and clothes, because fibres hold scent longer than skin does.\nHow is this different from a body spray? | A body spray has a lighter scent that fades within an hour or two. Koh-e-Noor uses more fragrance oil, so it lasts longer and smells richer.\nCan I spray it on clothes? | Yes, most fabrics are fine. Test on a hidden spot first on silk and very light colours.",
			'howto'        => "Hold the bottle about 20 cm away.\nSpray 2–3 times over the lengths of your hair, not the roots.\nAdd a spray to your neck, wrists and clothes.\nTop up during the day as you like.",
			'inci'         => 'Alcohol Denat., Aqua, Parfum (Fragrance), Glycerin, Panthenol, Polysorbate 20, Benzyl Salicylate, Coumarin, Limonene, Linalool.',
			'description'  => "Vanilla Pistachio opens with roasted pistachio and juicy pear, softens into vanilla orchid and almond milk, and settles on white musk and sandalwood. It smells sweet without being sugary.\n\nSpray it on your hair, neck and clothes. Hair and fabric hold scent longer than skin, so the mist lasts well into the evening.",
			'subtitle'     => 'Long-lasting scent for hair, skin and clothes · 3–4 hours on skin, 6–8 hours on hair',
			'batch'        => 'KN-VP-2609',
			'mfg'          => '09/2026',
			'expiry'       => '09/2029',
		),
		'NX-KN-VP-30'  => array( 'group' => 'koh-e-noor-vanilla', 'choice' => '30 ml', 'choice_tag' => 'Travel size' ),
		'NX-KN-OUD'    => array(
			'scent_group' => 'koh-e-noor-mists',
			'scent'       => 'Oud Amber',
			'notes'       => "Top | Saffron, pink pepper\nHeart | Rose, oud accord\nBase | Amber, vanilla, cedar",
			'wear'        => "Skin | 45 | 3–4 h\nHair | 90 | 6–8 h\nClothes | 100 | 6–8 h+",
		),
		'NX-KN-MUSK'   => array(
			'scent_group' => 'koh-e-noor-mists',
			'scent'       => 'Fresh Musk',
			'notes'       => "Top | Bergamot, pear\nHeart | Cotton flower, jasmine\nBase | White musk, ambrette",
			'wear'        => "Skin | 40 | 3 h\nHair | 85 | 6 h\nClothes | 100 | 6–8 h+",
		),
	),
	'categories' => array(
		'Skincare'      => array( 'order' => 1, 'shape' => 'dropper', 'tone' => '#e2a33b', 'tile' => '#fbf1df', 'short' => 'Serums, cleansers, creams', 'note' => 'Serums, moisturisers and cleansers that already sell in Pakistan, plus a mini to try first.' ),
		'Sun care'      => array( 'order' => 2, 'shape' => 'tube', 'tone' => '#f0c24b', 'tile' => '#fdf5dc', 'short' => 'SPF, sticks, tinted', 'note' => 'Creams lead today. Sticks and sun serums are the next wave.' ),
		'Hair care'     => array( 'order' => 3, 'shape' => 'bottle', 'tone' => '#c68a3a', 'tile' => '#f8eedf', 'short' => 'Hair fall, masks, oils', 'note' => 'Hair fall is the number one hair worry. Derm shampoos win it.' ),
		'Body care'     => array( 'order' => 4, 'shape' => 'pump', 'tone' => '#d9b48f', 'tile' => '#f7efe6', 'short' => 'Lotions, washes, gels', 'note' => 'Body care with actives is still a small shelf in Pakistan, so these stand out.' ),
		'Fragrance'     => array( 'order' => 5, 'shape' => 'perfume', 'tone' => '#b04a6b', 'tile' => '#f7e5eb', 'short' => 'Mists, perfume, decants', 'note' => 'Sweet and oud scents lead. Our Koh-e-Noor mists sit between body sprays and perfume.' ),
		'Makeup'        => array( 'order' => 6, 'shape' => 'lipstick', 'tone' => '#9e2f4a', 'tile' => '#f6e2e7', 'short' => 'Lips, blush, face', 'note' => 'Local matte lipsticks under Rs 500 sell the most.' ),
		'Men'           => array( 'order' => 7, 'shape' => 'tube', 'tone' => '#3c3f44', 'tile' => '#e8e9eb', 'short' => 'Face wash, beard, sprays', 'note' => 'Simple, proven basics for men.' ),
		'Personal care' => array( 'order' => 8, 'shape' => 'jar', 'tone' => '#9bb79e', 'tile' => '#eaf2eb', 'short' => 'Razors, hygiene', 'note' => 'Everyday essentials that sell every month.' ),
	),
	'brands'     => array(
		'Rederm'           => array( 'origin' => 'local', 'note' => 'Pakistan · Derm', 'derm' => '1', 'desc' => 'Hair fall, acne' ),
		'Estelin'          => array( 'origin' => 'local', 'note' => 'Pakistan · Derm', 'derm' => '1', 'desc' => 'Sunscreen, vitamin C' ),
		'Neophar'          => array( 'origin' => 'local', 'note' => 'Pakistan · Derm', 'derm' => '1', 'desc' => 'Sunscreen' ),
		'Jenpharm'         => array( 'origin' => 'local', 'note' => 'Pakistan · Derm', 'derm' => '1', 'desc' => 'Hair growth, biotin' ),
		'Medora'           => array( 'origin' => 'local', 'note' => 'Pakistan · Makeup' ),
		'Koh-e-Noor'       => array( 'origin' => 'local', 'note' => 'Our own label' ),
		'Hype by Capri'    => array( 'origin' => 'local', 'note' => 'Pakistan · Fragrance' ),
		'Swiss Miss'       => array( 'origin' => 'local', 'note' => 'Pakistan · Makeup' ),
		'Rivaj'            => array( 'origin' => 'local', 'note' => 'Pakistan' ),
		'AXIS-Y'           => array( 'origin' => 'intl', 'note' => 'Korea' ),
		'Dr. Althea'       => array( 'origin' => 'intl', 'note' => 'Korea' ),
		'Beauty of Joseon' => array( 'origin' => 'intl', 'note' => 'Korea' ),
		'Medicube'         => array( 'origin' => 'intl', 'note' => 'Korea' ),
		'Anua'             => array( 'origin' => 'intl', 'note' => 'Korea' ),
		'Tocobo'           => array( 'origin' => 'intl', 'note' => 'Korea' ),
		'SKIN1004'         => array( 'origin' => 'intl', 'note' => 'Korea' ),
		'Fino'             => array( 'origin' => 'intl', 'note' => 'Japan' ),
		'Feather'          => array( 'origin' => 'intl', 'note' => 'Japan' ),
		'Mielle'           => array( 'origin' => 'intl', 'note' => 'USA' ),
		'Vaseline'         => array( 'origin' => 'intl', 'note' => 'USA' ),
		'Gillette'         => array( 'origin' => 'intl', 'note' => 'USA' ),
		'St. Ives'         => array( 'origin' => 'intl', 'note' => 'USA' ),
		'Cetaphil'         => array( 'origin' => 'intl', 'note' => 'Canada' ),
		"L'Oréal Paris"    => array( 'origin' => 'intl', 'note' => 'France' ),
		'Garnier'          => array( 'origin' => 'intl', 'note' => 'France' ),
		'Garnier Men'      => array( 'origin' => 'intl', 'note' => 'France' ),
		"Pond's"           => array( 'origin' => 'intl', 'note' => 'UK' ),
		'Dove'             => array( 'origin' => 'intl', 'note' => 'UK' ),
	),
);
