<?php
/**
 * Starter catalogue imported on activation (only when the store has no products).
 * Prices come from Pakistani store research (Sept 2026). Items marked 'estimate' should be checked.
 *
 * @package NexusBeauty
 */

defined( 'ABSPATH' ) || exit;

return array(
	array(
		'sku' => 'NX-AXIS-Y-5',
		'name' => 'AXIS-Y Dark Spot Correcting Glow Serum',
		'short' => 'Pakistan\'s most-reviewed serum. The mini sells as well as the 50 ml.',
		'regular' => '799',
		'sale' => '',
		'category' => 'Skincare',
		'tags' => 'Mini, Korea, Bestseller, Dark spots, Dullness',
		'brand' => 'AXIS-Y',
		'cross' => 'NX-BOJ-RELIEF-SUN, NX-LOREAL-GLYCOLIC, NX-PONDS-GEL',
		'meta' => array(
			'_nx_tagline' => 'Pakistan\'s most-reviewed serum. The mini sells as well as the 50 ml.',
			'_nx_size' => '5 ml mini',
			'_nx_volume' => '5',
			'_nx_unit' => 'ml',
			'_nx_batch' => 'AX2609K',
			'_nx_mfg' => '03/2026',
			'_nx_expiry' => '02/2029',
			'_nx_good_for' => 'Dark spots or sun spots
Marks left behind by acne
Dull, uneven skin tone
Oily, combination or normal skin',
			'_nx_not_for' => 'You have active, painful breakouts
Your skin is very dry and tight
You won\'t wear sunscreen daily',
			'_nx_ingredients' => 'Niacinamide 5% | Main active | Helps fade dark spots, evens tone and controls oil
Sea buckthorn | Antioxidant | Helps skin look brighter
Mulberry & licorice | Tone support | Plant extracts used to help even out skin tone
Squalane | Hydration | Light moisture without a greasy finish',
			'_nx_howto' => 'Wash with a gentle face wash.
Press 2-3 drops into face and neck, morning and night.
Moisturise if your skin feels dry.
In the morning, finish with SPF 50.',
			'_nx_faq' => 'How soon will I see results? | Most people see a brighter look in 1-2 weeks and lighter marks in 4-8 weeks, with daily sunscreen.
Can I use it with vitamin C or retinol? | Yes. Use vitamin C in the morning and retinol at night.
Which size should I buy? | Start with the 5 ml mini to test it. The 50 ml costs about half as much per ml.',
		),
	),
	array(
		'sku' => 'NX-AXIS-Y-50',
		'name' => 'AXIS-Y Dark Spot Correcting Glow Serum',
		'short' => 'Full size of the serum Pakistan reviews most',
		'regular' => '4049',
		'sale' => '',
		'category' => 'Skincare',
		'tags' => 'Korea, Dark spots, Dullness',
		'brand' => 'AXIS-Y',
		'cross' => 'NX-BOJ-RELIEF-SUN, NX-LOREAL-GLYCOLIC, NX-PONDS-GEL',
		'meta' => array(
			'_nx_tagline' => 'Full size of the serum Pakistan reviews most',
			'_nx_size' => '50 ml',
			'_nx_volume' => '50',
			'_nx_unit' => 'ml',
			'_nx_batch' => 'AX2609K',
			'_nx_mfg' => '03/2026',
			'_nx_expiry' => '02/2029',
			'_nx_good_for' => 'Dark spots or sun spots
Marks left behind by acne
Dull, uneven skin tone
Oily, combination or normal skin',
			'_nx_not_for' => 'You have active, painful breakouts
Your skin is very dry and tight
You won\'t wear sunscreen daily',
			'_nx_ingredients' => 'Niacinamide 5% | Main active | Helps fade dark spots, evens tone and controls oil
Sea buckthorn | Antioxidant | Helps skin look brighter
Mulberry & licorice | Tone support | Plant extracts used to help even out skin tone
Squalane | Hydration | Light moisture without a greasy finish',
			'_nx_howto' => 'Wash with a gentle face wash.
Press 2-3 drops into face and neck, morning and night.
Moisturise if your skin feels dry.
In the morning, finish with SPF 50.',
			'_nx_faq' => 'How soon will I see results? | Most people see a brighter look in 1-2 weeks and lighter marks in 4-8 weeks, with daily sunscreen.
Can I use it with vitamin C or retinol? | Yes. Use vitamin C in the morning and retinol at night.
Which size should I buy? | Start with the 5 ml mini to test it. The 50 ml costs about half as much per ml.',
		),
	),
	array(
		'sku' => 'NX-DR-ALTHEA-345',
		'name' => 'Dr. Althea 345 Relief Cream',
		'short' => 'Light barrier repair that suits the heat',
		'regular' => '2749',
		'sale' => '',
		'category' => 'Skincare',
		'tags' => 'Korea, Bestseller, Dryness, Sensitive skin',
		'brand' => 'Dr. Althea',
		'cross' => 'NX-BOJ-RELIEF-SUN, NX-CETAPHIL-GENTLE',
		'meta' => array(
			'_nx_tagline' => 'Light barrier repair that suits the heat',
			'_nx_size' => '50 ml',
			'_nx_volume' => '50',
			'_nx_unit' => 'ml',
		),
	),
	array(
		'sku' => 'NX-PONDS-GEL',
		'name' => 'Pond\'s Super Light Gel Moisturiser',
		'short' => 'A light gel for oily skin in summer',
		'regular' => '749',
		'sale' => '',
		'category' => 'Skincare',
		'tags' => 'Dryness',
		'brand' => 'Pond\'s',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'A light gel for oily skin in summer',
			'_nx_size' => '50 ml',
			'_nx_volume' => '50',
			'_nx_unit' => 'ml',
		),
	),
	array(
		'sku' => 'NX-LOREAL-GLYCOLIC',
		'name' => 'L\'Oréal Paris Glycolic Bright Face Wash',
		'short' => 'The best-selling "bright" cleanser',
		'regular' => '999',
		'sale' => '',
		'category' => 'Skincare',
		'tags' => 'Dark spots, Dullness',
		'brand' => 'L\'Oréal Paris',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'The best-selling "bright" cleanser',
		),
	),
	array(
		'sku' => 'NX-GARNIER-VITC',
		'name' => 'Garnier Bright Complete Vitamin C Serum',
		'short' => 'An easy first vitamin C at a low price',
		'regular' => '550',
		'sale' => '',
		'category' => 'Skincare',
		'tags' => 'Dullness, Dark spots',
		'brand' => 'Garnier',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'An easy first vitamin C at a low price',
		),
	),
	array(
		'sku' => 'NX-MEDICUBE-PDRN',
		'name' => 'Medicube PDRN Pink Peptide Serum',
		'short' => 'The number one product on US TikTok Shop this spring',
		'regular' => '3829',
		'sale' => '',
		'category' => 'Skincare',
		'tags' => 'Korea, Dullness, Dryness',
		'brand' => 'Medicube',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'The number one product on US TikTok Shop this spring',
		),
	),
	array(
		'sku' => 'NX-ANUA-AZELAIC',
		'name' => 'Anua Azelaic Acid 10 Hyaluron Redness Soothing Serum',
		'short' => 'For redness, bumps and post-acne marks',
		'regular' => '6659',
		'sale' => '',
		'category' => 'Skincare',
		'tags' => 'Korea, Acne, Sensitive skin, Dark spots',
		'brand' => 'Anua',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'For redness, bumps and post-acne marks',
		),
	),
	array(
		'sku' => 'NX-BOJ-RELIEF-SUN',
		'name' => 'Beauty of Joseon Relief Sun SPF 50+',
		'short' => 'The sunscreen with the most reviews in Pakistan',
		'regular' => '1299',
		'sale' => '',
		'category' => 'Sun care',
		'tags' => 'Korea, Bestseller, Sun protection, Dark spots',
		'brand' => 'Beauty of Joseon',
		'cross' => 'NX-AXIS-Y-5, NX-GARNIER-VITC',
		'meta' => array(
			'_nx_tagline' => 'The sunscreen with the most reviews in Pakistan',
			'_nx_size' => '50 ml',
			'_nx_volume' => '50',
			'_nx_unit' => 'ml',
		),
	),
	array(
		'sku' => 'NX-ESTELIN-70',
		'name' => 'Estelin Tinted Sunscreen SPF 70',
		'short' => 'A Pakistani derm favourite with no white cast',
		'regular' => '1239',
		'sale' => '',
		'category' => 'Sun care',
		'tags' => 'Derm, Pakistani, Bestseller, Sun protection, Dark spots',
		'brand' => 'Estelin',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'A Pakistani derm favourite with no white cast',
		),
	),
	array(
		'sku' => 'NX-NEOBRELLA-60',
		'name' => 'Neophar Neobrella Sunscreen SPF 60',
		'short' => 'Derm-brand sun cream under Rs 1,000',
		'regular' => '930',
		'sale' => '',
		'category' => 'Sun care',
		'tags' => 'Derm, Pakistani, Sun protection',
		'brand' => 'Neophar',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'Derm-brand sun cream under Rs 1,000',
		),
	),
	array(
		'sku' => 'NX-TOCOBO-STICK',
		'name' => 'Tocobo Cotton Soft Sun Stick SPF 50+',
		'short' => 'Reapply over makeup or on the go',
		'regular' => '4509',
		'sale' => '',
		'category' => 'Sun care',
		'tags' => 'Korea, Sun protection',
		'brand' => 'Tocobo',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'Reapply over makeup or on the go',
		),
	),
	array(
		'sku' => 'NX-SKIN1004-SUN',
		'name' => 'SKIN1004 Hyalu-Cica Water-fit Sun Serum',
		'short' => 'SPF that feels like a serum',
		'regular' => '4289',
		'sale' => '',
		'category' => 'Sun care',
		'tags' => 'Korea, Sun protection, Sensitive skin',
		'brand' => 'SKIN1004',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'SPF that feels like a serum',
		),
	),
	array(
		'sku' => 'NX-REDERM-TRESSFIX',
		'name' => 'Rederm Tressfix Hairfall & Anti-Dandruff Shampoo',
		'short' => 'Pakistan\'s number one hair fall shampoo online',
		'regular' => '1150',
		'sale' => '',
		'category' => 'Hair care',
		'tags' => 'Derm, Pakistani, Bestseller, Hair fall, Dandruff',
		'brand' => 'Rederm',
		'cross' => 'NX-JENPHARM-ANAGROW, NX-FINO-MASK',
		'meta' => array(
			'_nx_tagline' => 'Pakistan\'s number one hair fall shampoo online',
		),
	),
	array(
		'sku' => 'NX-JENPHARM-ANAGROW',
		'name' => 'Jenpharm Anagrow Biotin Shampoo',
		'short' => 'Biotin shampoo from a trusted derm brand',
		'regular' => '988',
		'sale' => '',
		'category' => 'Hair care',
		'tags' => 'Derm, Pakistani, Hair fall',
		'brand' => 'Jenpharm',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'Biotin shampoo from a trusted derm brand',
		),
	),
	array(
		'sku' => 'NX-FINO-MASK',
		'name' => 'Fino Premium Touch Hair Mask',
		'short' => 'The best-loved mask for dry, damaged hair',
		'regular' => '3299',
		'sale' => '',
		'category' => 'Hair care',
		'tags' => 'Bestseller, Frizz',
		'brand' => 'Fino',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'The best-loved mask for dry, damaged hair',
		),
	),
	array(
		'sku' => 'NX-MIELLE-ROSEMARY',
		'name' => 'Mielle Rosemary Mint Strengthening Hair Masque',
		'short' => 'The rosemary original that started the trend',
		'regular' => '4079',
		'sale' => '',
		'category' => 'Hair care',
		'tags' => 'Hair fall, Frizz',
		'brand' => 'Mielle',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'The rosemary original that started the trend',
		),
	),
	array(
		'sku' => 'NX-VASELINE-GLUTA',
		'name' => 'Vaseline Gluta-Hya Serum Burst Lotion',
		'short' => 'The body lotion with actives Pakistan buys most',
		'regular' => '2399',
		'sale' => '',
		'category' => 'Body care',
		'tags' => 'Bestseller, Body glow, Dullness',
		'brand' => 'Vaseline',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'The body lotion with actives Pakistan buys most',
		),
	),
	array(
		'sku' => 'NX-VASELINE-GEL-OIL',
		'name' => 'Vaseline Intensive Care Body Gel Oil',
		'short' => 'Glow without the grease',
		'regular' => '3439',
		'sale' => '',
		'category' => 'Body care',
		'tags' => 'Body glow, Dryness',
		'brand' => 'Vaseline',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'Glow without the grease',
		),
	),
	array(
		'sku' => 'NX-KN-VP',
		'name' => 'Koh-e-Noor Vanilla Pistachio Hair & Body Mist',
		'short' => 'Our own mist. Launch price.',
		'regular' => '1450',
		'sale' => '1290',
		'category' => 'Fragrance',
		'tags' => 'Our label, Bestseller, Long-lasting scent',
		'brand' => 'Koh-e-Noor by Nexus Beauty',
		'cross' => 'NX-VASELINE-GLUTA, NX-KN-OUD',
		'meta' => array(
			'_nx_tagline' => 'Our own mist. Launch price.',
			'_nx_size' => '100 ml',
			'_nx_volume' => '100',
			'_nx_unit' => 'ml',
		),
	),
	array(
		'sku' => 'NX-KN-OUD',
		'name' => 'Koh-e-Noor Oud Amber Hair & Body Mist',
		'short' => 'Warm oud, light enough for every day',
		'regular' => '1450',
		'sale' => '1290',
		'category' => 'Fragrance',
		'tags' => 'Our label, Long-lasting scent',
		'brand' => 'Koh-e-Noor by Nexus Beauty',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'Warm oud, light enough for every day',
			'_nx_size' => '100 ml',
			'_nx_volume' => '100',
			'_nx_unit' => 'ml',
		),
	),
	array(
		'sku' => 'NX-KN-MUSK',
		'name' => 'Koh-e-Noor Fresh Musk Hair & Body Mist',
		'short' => 'Clean cotton and white musk',
		'regular' => '1450',
		'sale' => '1290',
		'category' => 'Fragrance',
		'tags' => 'Our label, Long-lasting scent',
		'brand' => 'Koh-e-Noor by Nexus Beauty',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'Clean cotton and white musk',
			'_nx_size' => '100 ml',
			'_nx_volume' => '100',
			'_nx_unit' => 'ml',
		),
	),
	array(
		'sku' => 'NX-KN-VP-30',
		'name' => 'Koh-e-Noor Vanilla Pistachio Mist, travel size',
		'short' => 'Try the scent before the full size',
		'regular' => '490',
		'sale' => '',
		'category' => 'Fragrance',
		'tags' => 'Our label, Mini, Long-lasting scent',
		'brand' => 'Koh-e-Noor by Nexus Beauty',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'Try the scent before the full size',
			'_nx_size' => '30 ml',
			'_nx_volume' => '30',
			'_nx_unit' => 'ml',
		),
	),
	array(
		'sku' => 'NX-HYPE-FRUIT',
		'name' => 'Hype by Capri Fruit Frenzy Body Spray',
		'short' => 'The best-selling sweet body spray',
		'regular' => '550',
		'sale' => '',
		'category' => 'Fragrance',
		'tags' => 'Pakistani, Long-lasting scent',
		'brand' => 'Hype by Capri',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'The best-selling sweet body spray',
			'_nx_size' => '150 ml',
			'_nx_volume' => '150',
			'_nx_unit' => 'ml',
		),
	),
	array(
		'sku' => 'NX-MEDORA-MATTE',
		'name' => 'Medora Matte Lipstick',
		'short' => 'Pakistan\'s most-reviewed lipstick',
		'regular' => '300',
		'sale' => '',
		'category' => 'Makeup',
		'tags' => 'Pakistani, Bestseller, Lips',
		'brand' => 'Medora',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'Pakistan\'s most-reviewed lipstick',
		),
	),
	array(
		'sku' => 'NX-SWISS-MISS-60',
		'name' => 'Swiss Miss Natural Matte Lipstick 60',
		'short' => 'A local matte favourite',
		'regular' => '400',
		'sale' => '',
		'category' => 'Makeup',
		'tags' => 'Pakistani, Lips',
		'brand' => 'Swiss Miss',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'A local matte favourite',
		),
	),
	array(
		'sku' => 'NX-GARNIER-MEN-ACNO',
		'name' => 'Garnier Men Acno Fight Face Wash',
		'short' => 'For oily, acne-prone skin',
		'regular' => '1050',
		'sale' => '',
		'category' => 'Men',
		'tags' => 'Acne, Men',
		'brand' => 'Garnier Men',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'For oily, acne-prone skin',
		),
	),
	array(
		'sku' => 'NX-RIVAJ-BEARD',
		'name' => 'Rivaj Beard Oil',
		'short' => 'Softens and tames the beard',
		'regular' => '695',
		'sale' => '',
		'category' => 'Men',
		'tags' => 'Pakistani, Men',
		'brand' => 'Rivaj',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'Softens and tames the beard',
		),
	),
	array(
		'sku' => 'NX-DAISY-PLUS',
		'name' => 'Gillette Daisy Plus Razors',
		'short' => 'The top hair removal pick online',
		'regular' => '599',
		'sale' => '',
		'category' => 'Personal care',
		'tags' => '',
		'brand' => 'Gillette',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'The top hair removal pick online',
		),
	),
	array(
		'sku' => 'NX-ST-IVES-APRICOT',
		'name' => 'St. Ives Fresh Skin Apricot Face Scrub',
		'short' => 'Weekly exfoliation for smoother, brighter skin',
		'regular' => '1299',
		'sale' => '',
		'category' => 'Skincare',
		'tags' => 'Dullness, Dark spots',
		'brand' => 'St. Ives',
		'cross' => '',
		'estimate' => true,
		'meta' => array(
			'_nx_tagline' => 'Weekly exfoliation for smoother, brighter skin',
		),
	),
	array(
		'sku' => 'NX-DOVE-BODY-POLISH',
		'name' => 'Dove Exfoliating Body Polish',
		'short' => 'Buffs away dry, rough skin on the body',
		'regular' => '2499',
		'sale' => '',
		'category' => 'Body care',
		'tags' => 'Body glow, Dullness',
		'brand' => 'Dove',
		'cross' => '',
		'estimate' => true,
		'meta' => array(
			'_nx_tagline' => 'Buffs away dry, rough skin on the body',
		),
	),
	array(
		'sku' => 'NX-CETAPHIL-GENTLE',
		'name' => 'Cetaphil Gentle Skin Cleanser',
		'short' => 'A soap-free cleanser for dry and sensitive skin',
		'regular' => '2199',
		'sale' => '',
		'category' => 'Skincare',
		'tags' => 'Dryness, Sensitive skin',
		'brand' => 'Cetaphil',
		'cross' => '',
		'estimate' => true,
		'meta' => array(
			'_nx_tagline' => 'A soap-free cleanser for dry and sensitive skin',
		),
	),
	array(
		'sku' => 'NX-REDERM-CLARIDERM',
		'name' => 'Rederm Clariderm Face Wash',
		'short' => 'A derm-brand wash for oily, acne-prone skin',
		'regular' => '1050',
		'sale' => '',
		'category' => 'Skincare',
		'tags' => 'Derm, Pakistani, Acne',
		'brand' => 'Rederm',
		'cross' => '',
		'estimate' => true,
		'meta' => array(
			'_nx_tagline' => 'A derm-brand wash for oily, acne-prone skin',
		),
	),
	array(
		'sku' => 'NX-FEATHER-FLAMINGOS',
		'name' => 'Feather Flamingos Facial Razor',
		'short' => 'For quick, painless facial hair removal',
		'regular' => '999',
		'sale' => '',
		'category' => 'Personal care',
		'tags' => 'Imported',
		'brand' => 'Feather',
		'cross' => '',
		'meta' => array(
			'_nx_tagline' => 'For quick, painless facial hair removal',
			'_nx_size' => 'Pack',
		),
	),
);
